# domain.py — mapping English domain keys to Serbian

from typing import Any, Dict

UNKNOWN_DOMAIN = "nepoznato"

DOMAIN_MAP: Dict[str, str] = {
    "sociology": "sociologija",
    "psychiatry": "psihijatrija",
    "factotum": "opšta upotreba",
    "chemistry": "hemija",
    "physiology": "fiziologija",
    "literature": "književnost",
    "biology": "biologija",
    "medicine": "medicina",
    "administration": "administracija",
    "politics": "politika",
    "town_planning": "urbanizam",
    "geography": "geografija",
    "enterprise": "preduzetništvo",
    "person": "osoba",
    "psychology": "psihologija",
    "zoology": "zoologija",
    "school": "škola",
    "anthropology": "antropologija",
    "linguistics": "lingvistika",
    "art": "umetnost",
    "mechanics": "mehanika",
    "play": "dramsko delo",
    "exchange": "razmena",
    "painting": "slikarstvo",
    "law": "pravo",
    "grammar": "gramatika",
    "building_industry": "građevinska industrija",
    "publishing": "izdavaštvo",
    "music": "muzika",
    "mathematics": "matematika",
    "alimentation": "ishrana",
    "metrology": "metrologija",
    "pharmacy": "farmacija",
    "physics": "fizika",
    "cinema": "kinematografija",
    "philology": "filologija",
    "occultism": "okultizam",
    "philosophy": "filozofija",
    "quality": "kvalitet",
    "religion": "religija",
    "architecture": "arhitektura",
    "computer_science": "računarske nauke",
    "military": "vojna nauka",
    "geometry": "geometrija",
    "astronomy": "astronomija",
    "astronautics": "astronautika",
    "meteorology": "meteorologija",
    "tourism": "turizam",
    "transport": "transport",
    "botany": "botanika",
    "banking": "bankarstvo",
    "economy": "ekonomija",
    "furniture": "nameštaj",
    "commerce": "trgovina",
    "heraldry": "heraldika",
    "atomic_physic": "atomska fizika",
    "basketball": "košarka",
    "free_time": "slobodno vreme",
    "cycling": "biciklizam",
    "sport": "sport",
    "telephony": "telefonija",
    "history": "istorija",
    "artisanship": "zanatstvo",
    "color": "boja",
    "merchant_navy": "trgovačka mornarica",
    "boxing": "boks",
    "mythology": "mitologija",
    "gastronomy": "gastronomska umetnost",
    "number": "broj",
    "anatomy": "anatomiја",
    "money": "novac",
    "time_period": "vremenski period",
    "entomology": "entomologija",
    "hydraulics": "hidraulika",
    "dance": "ples",
    "drawing": "crtanje",
    "optics": "optika",
    "diplomacy": "diplomatija",
    "electricity": "elektricitet",
    "ethnology": "etnologija",
    "industry": "industrija",
    "card": "karte",
    "betting": "kockanje",
    "agriculture": "poljoprivreda",
    "telecommunication": "telekomunikacije",
    "doctrines": "doktrine",
    "acoustics": "akustika",
    "ecology": "ekologija",
    "photography": "fotografija",
    "radiology": "radiologija",
    "geology": "geologija",
    "sexuality": "seksualnost",
    "archaeology": "arheologija",
    "football": "fudbal",
    "theatre": "pozorište",
    "hockey": "hokej",
    "fashion": "moda",
    "pure_science": "osnovne nauke",
    "baseball": "bejzbol",
    "social_science": "društvene nauke",
    "engineering": "inženjering",
    "pedagogy": "pedagogija",
    "post": "pošta",
    "body_care": "nega tela",
    "earth": "zemlja",
    "tv": "televizija",
    "roman_catholic": "rimsko-katolički",
    "athletics": "atletika",
    "chess": "šah",
    "racing": "trke",
    "dentistry": "stomatologija",
    "oceanography": "oceanografija",
    "aeronautic": "aeronautika",
    "railway": "željeznica",
    "soccer": "fudbal",
    "jewellery": "nakit",
    "insurance": "osiguranje",
    "statistics": "statistika",
    "surgery": "hirurgija",
    "fishing": "ribolov",
    "mountaineering": "planinarenje",
    "swimming": "plivanje",
    "electronics": "elektronika",
    "genetics": "genetika",
    "auto": "automobili",
    "psychological_features": "psihološke karakteristike",
    "sculpture": "skulptura",
    "theology": "teologija",
    "plants": "biljke",
    "tax": "porezi",
    "food": "hrana",
}

def translate_domain(domain: Any) -> str:
    """
    Return the Serbian translation for a given English domain key.
    If 'domain' is None or NaN, or not found in the map, returns UNKNOWN_DOMAIN.
    """
    # NaN is the only value in Python that doesn't equal itself
    if domain is None or (isinstance(domain, float) and domain != domain):
        return UNKNOWN_DOMAIN

    return DOMAIN_MAP.get(domain, UNKNOWN_DOMAIN)
